In [1]:
import tensorflow as tf
import cv2
import numpy as np

from IPython.display import Image

import viz_utils

In [2]:
img = cv2.imread("test_img.png")

In [3]:
img = img.transpose([2,0,1])

In [4]:
img.shape

(3, 28, 28)

In [5]:
img = img.astype(np.float32)

In [6]:
img = np.expand_dims(img, axis=0)

In [7]:
img.shape

(1, 3, 28, 28)

In [8]:
def get_random_filter(num_filters, filter_channels, filter_height, filter_width, seed=10):
    np.random.seed(seed)
    
    return np.random.randn(num_filters, filter_channels, filter_height, filter_width)

In [9]:
conv_filters = get_random_filter(5, 3, 3, 3)

In [10]:
## TF requires 4d array as conv
# format of filters for TF --> [filter_height, filter_width, in_channels, out_channels]

In [11]:
conv_filters = conv_filters.transpose([2, 3, 1, 0])

In [12]:
conv_filters.shape

(3, 3, 3, 5)

In [13]:
conv_out = tf.nn.conv2d(img, conv_filters, strides = 1, padding = 'SAME', data_format = "NCHW").numpy()

In [14]:
conv_out.shape

(1, 5, 28, 28)

In [15]:
conv_out = conv_out.squeeze()

In [16]:
conv_out.shape

(5, 28, 28)

In [17]:
# conv_out = conv_out.astype(np.uint8)

In [18]:
conv_filters[0]

array([[[ 1.3315865 ,  1.39799638,  0.84222474,  1.74481415,
          0.70683045],
        [-0.17460021,  0.40020999, -0.69781003,  1.10770823,
          0.14110417],
        [ 1.484537  , -0.21269764, -0.21578989, -1.95451212,
          1.02251611]],

       [[ 0.71527897, -0.27124799,  0.2035808 , -1.85618548,
         -0.78726893],
        [ 0.43302619, -0.33763234, -0.08112218,  0.24454398,
          0.27304932],
        [-1.07980489, -0.33914025,  0.98907246,  0.11747566,
          0.16681027]],

       [[-1.54540029,  0.61320418,  2.39470366, -0.2227737 ,
          0.29294072],
        [ 1.20303737,  1.25647226, -0.52929608, -0.06191203,
         -1.61857075],
        [-1.97772828,  0.31216994,  0.31475378, -1.90745689,
          1.65671662]]])

In [19]:
conv_filters_transposed = conv_filters.transpose([3, 2, 0, 1])

In [20]:
conv_filters_transposed[1]

array([[[ 1.39799638, -0.27124799,  0.61320418],
        [-0.26731719, -0.54930901,  0.1327083 ],
        [-0.47614201,  1.30847308,  0.19501328]],

       [[ 0.40020999, -0.33763234,  1.25647226],
        [-0.7319695 ,  0.66023155, -0.35087189],
        [-0.93943336, -0.48933722, -0.80459114]],

       [[-0.21269764, -0.33914025,  0.31216994],
        [ 0.56515267, -0.14742026, -0.02590534],
        [ 0.2890942 , -0.53987907,  0.70816002]]])

In [ ]:
array([[[ 1.39799638, -0.27124799,  0.61320418],
        [-0.26731719, -0.54930901,  0.1327083 ],
        [-0.47614201,  1.30847308,  0.19501328]],

       [[ 0.40020999, -0.33763234,  1.25647226],
        [-0.7319695 ,  0.66023155, -0.35087189],
        [-0.93943336, -0.48933722, -0.80459114]],

       [[-0.21269764, -0.33914025,  0.31216994],
        [ 0.56515267, -0.14742026, -0.02590534],
        [ 0.2890942 , -0.53987907,  0.70816002]]])

In [26]:
viz_utils.vis_2darray(conv_out[1])

0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0

0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0

0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0

0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0

0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0

0.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0

0.00.00.00.00.08.28090341.695286-27.28735-149.11127-131.02779-149.79428-57.53563-40.553320.00.00.00.00.00.00.00.00.00.00.00.00.00.00.0

0.00.00.00.00.01.383465538.81633-236.13397-313.1274-279.33768-267.96725-226.66801-212.29866-148.23119-148.23119-148.23119-148.23119-148.23119-148.23119-150.99149-170.44336-176.98045-58.577020.00.00.00.00.0

0.00.00.00.00.0135.6968283.86044100.529755193.4347225.11913522.194178-201.5751-265.69916-339.76425-298.99786-331.6658-332.06012-335.2474-334.

In [41]:
conv_out[0][7]

array([   0.      ,    0.      ,    0.      ,    0.      ,    0.      ,
        212.0192  ,  714.9097  , 1058.799   ,  778.143   ,  661.1453  ,
        460.00723 ,  574.45703 ,  519.13336 ,  538.0623  ,  538.0623  ,
        538.0623  ,  538.0623  ,  538.0623  ,  538.0623  ,  531.38214 ,
        485.1821  ,  345.35544 ,   95.385704,    0.      ,    0.      ,
          0.      ,    0.      ,    0.      ], dtype=float32)

In [44]:
conv_out[2].mean()

134.25172

In [36]:
conv_out.shape

(5, 28, 28)

In [18]:
cv2.imwrite("conv_out_tf.png", conv_out)

True

In [21]:
Image("conv_out_tf.png", height=250, width = 250)

In [23]:
viz_utils.vis_2darray(conv_out)

   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

   0   0   0   0   0 164 241 216 103 230  43 112 148   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

   0   0   0   0   0 170  53 107 207 100  85  29 209  82  82  82  82  82  82 198  92  54 100   0   0   0   0   0

   0   0   0   0   0 129 240 254 118 158 100 212  48  47 163  76  56 203  63 123  72 250